import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { isIP } from 'node:net'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const hostKeys = ['cognitoAuth', 'cognitoJwks', 'essentia', 'codebuild', 'kvs', 'lambda']
const invalid = () => { throw new TypeError('Invalid egress configuration') }
const plainObject = value => value !== null && typeof value === 'object' && !Array.isArray(value)
const exactKeys = (value, keys) => plainObject(value) && Object.keys(value).length === keys.length &&
  keys.every(key => Object.hasOwn(value, key))
const ipv4Number = value => value.split('.').reduce((number, part) => number * 256 + Number(part), 0)
const privateIpv4 = value => {
  if (typeof value !== 'string' || isIP(value) !== 4) return false
  const [a, b] = value.split('.').map(Number)
  return a === 10 || a === 172 && b >= 16 && b <= 31 || a === 192 && b === 168
}
function validateCidr(value) {
  if (typeof value !== 'string' || !/^\d+\.\d+\.\d+\.\d+\/(?:1[6-9]|2\d|3[0-2])$/.test(value)) invalid()
  const [network, prefix] = value.split('/')
  if (!privateIpv4(network)) invalid()
  const size = 2 ** (32 - Number(prefix))
  // Canonical, fully RFC1918 /16..32 networks only; no accidental host-bit widening.
  const start = ipv4Number(network)
  if (start % size !== 0 || !privateIpv4([24, 16, 8, 0].map(shift => (start + size - 1) >>> shift & 255).join('.'))) invalid()
  return value
}
function validateHost(value) {
  if (typeof value !== 'string' || value.length > 253 || isIP(value) || value !== value.toLowerCase() ||
    !/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z][a-z0-9-]*[a-z0-9]$/.test(value) ||
    value.split('.').some(label => label.length > 63)) invalid()
  return value
}

/** Pure rendering: no DNS, environment reads, Docker calls, or deployment side effects. */
export function renderConfig(input) {
  if (!exactKeys(input, ['privateIpv4', 'lambdaCidrs', 'hosts']) || !privateIpv4(input.privateIpv4) ||
    !Array.isArray(input.lambdaCidrs) || input.lambdaCidrs.length === 0 || input.lambdaCidrs.length > 32 ||
    !exactKeys(input.hosts, hostKeys)) invalid()
  const cidrs = [...new Set(input.lambdaCidrs.map(validateCidr))].sort()
  const hosts = [...new Set(hostKeys.map(key => validateHost(input.hosts[key])))].sort()
  const authority = `^(${hosts.map(host => host.replaceAll('.', '\\.')).join('|')}):443$`
  const squidConfig = `# Generated by infra/egress/render-config.mjs; no external includes/default ACLs.
visible_hostname icaros-egress
http_port ${input.privateIpv4}:3128
workers 1
pid_filename none
access_log none
cache_log /dev/null
cache_store_log none
logfile_rotate 0
debug_options ALL,0
cache deny all
cache_mem 0 MB
memory_pools off
netdb_filename none
pinger_enable off
icp_port 0
htcp_port 0
snmp_port 0
max_filedescriptors 256
ipcache_size 256
fqdncache_size 256
connect_timeout 5 seconds
dns_timeout 5 seconds
request_timeout 15 seconds
read_timeout 60 seconds
client_lifetime 2 minutes
pconn_timeout 15 seconds
persistent_request_timeout 15 seconds
shutdown_lifetime 5 seconds
half_closed_clients off
forwarded_for delete
httpd_suppress_version_string on
acl lambda_sources src ${cidrs.join(' ')}
acl tunnel method CONNECT
acl tls_port port 443
acl allowed_hosts dstdomain -n ${hosts.join(' ')}
acl exact_authority url_regex -i ${authority}
acl proxy_credentials req_header Proxy-Authorization .+
acl too_many_connections maxconn 16
http_access deny !lambda_sources
http_access deny !tunnel
http_access deny !tls_port
http_access deny proxy_credentials
http_access deny too_many_connections
http_access allow lambda_sources tunnel tls_port allowed_hosts exact_authority
http_access deny all
`
  // Fixed paths/tag avoid shell/systemd interpolation from untrusted deployment inputs.
  const systemdUnit = `[Unit]
Description=ICAROS bounded HTTPS CONNECT egress
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutStartSec=60
TimeoutStopSec=20
ExecStartPre=/usr/bin/docker image inspect icaros-egress:approved
ExecStartPre=-/usr/bin/docker rm -f icaros-egress
ExecStart=/usr/bin/docker run --detach --name=icaros-egress --platform=linux/arm64 --network=host --restart=unless-stopped --memory=128m --memory-swap=128m --cpus=0.25 --pids-limit=64 --ulimit=nofile=256:256 --read-only --cap-drop=ALL --security-opt=no-new-privileges:true --user=proxy --log-driver=none --tmpfs=/tmp:rw,noexec,nosuid,nodev,size=8m,mode=1777 --mount=type=bind,src=/etc/icaros-egress/squid.conf,dst=/etc/squid/squid.conf,readonly icaros-egress:approved
ExecStop=/usr/bin/docker stop --time=10 icaros-egress

[Install]
WantedBy=multi-user.target
`
  return { squidConfig, systemdUnit }
}

async function main() {
  const [, , inputPath, outputDirectory, ...extra] = process.argv
  if (!inputPath || !outputDirectory || extra.length) throw new Error('usage')
  const { squidConfig, systemdUnit } = renderConfig(JSON.parse(await readFile(inputPath, 'utf8')))
  await mkdir(outputDirectory, { recursive: true, mode: 0o700 })
  await writeFile(resolve(outputDirectory, 'squid.conf'), squidConfig, { mode: 0o600, flag: 'wx' })
  await writeFile(resolve(outputDirectory, 'icaros-egress.service'), systemdUnit, { mode: 0o600, flag: 'wx' })
}
if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  main().catch(() => {
    // Do not leak deployment hostnames, addresses, file contents, or parser errors.
    process.stderr.write('Egress rendering failed. Check input and use a fresh output directory.\n')
    process.exitCode = 1
  })
}
